/* Generated By:JavaCC: Do not edit this line. BasicConstants.java */
package customit;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BasicConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 16;
  /** RegularExpression Id. */
  int MINUS = 17;
  /** RegularExpression Id. */
  int MULTIPLY = 18;
  /** RegularExpression Id. */
  int DIVIDE = 19;
  /** RegularExpression Id. */
  int QUOTED_STRING = 20;
  /** RegularExpression Id. */
  int ME = 21;
  /** RegularExpression Id. */
  int MY_EMAIL = 22;
  /** RegularExpression Id. */
  int STATE = 23;
  /** RegularExpression Id. */
  int SENSOR = 24;
  /** RegularExpression Id. */
  int ALARM = 25;
  /** RegularExpression Id. */
  int WHEN = 26;
  /** RegularExpression Id. */
  int THEN = 27;
  /** RegularExpression Id. */
  int AT = 28;
  /** RegularExpression Id. */
  int IN = 29;
  /** RegularExpression Id. */
  int TIME = 30;
  /** RegularExpression Id. */
  int WHERE = 31;
  /** RegularExpression Id. */
  int CONSTANT = 32;
  /** RegularExpression Id. */
  int DIGIT = 33;
  /** RegularExpression Id. */
  int EOL = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"to\"",
    "\"from\"",
    "\"should\"",
    "\"please\"",
    "\"and\"",
    "\"the\"",
    "\"switch\"",
    "\"someone\"",
    "\"is\"",
    "\"ring\"",
    "\"plus\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<QUOTED_STRING>",
    "<ME>",
    "\"me email\"",
    "<STATE>",
    "<SENSOR>",
    "\"alarm\"",
    "\"when\"",
    "\"then\"",
    "\"at\"",
    "\"in\"",
    "<TIME>",
    "<WHERE>",
    "<CONSTANT>",
    "<DIGIT>",
    "\".\"",
  };

}
